  labels:
    0: "animal--bird"
    1: "animal--ground-animal"
    2: "construction--barrier--curb"
    3: "construction--barrier--fence"
    4: "construction--barrier--guard-rail"
    5: "construction--barrier--other-barrier"
    6: "construction--barrier--wall"
    7: "construction--flat--bike-lane"
    8: "construction--flat--crosswalk-plain"
    9: "construction--flat--curb-cut"
    10: "construction--flat--parking"
    11: "construction--flat--pedestrian-area"
    12: "construction--flat--rail-track"
    13: "construction--flat--road"
    14: "construction--flat--service-lane"
    15: "construction--flat--sidewalk"
    16: "construction--structure--bridge"
    17: "construction--structure--building"
    18: "construction--structure--tunnel"
    19: "human--person"
    20: "human--rider--bicyclist"
    21: "human--rider--motorcyclist"
    22: "human--rider--other-rider"
    23: "marking--crosswalk-zebra"
    24: "marking--general"
    25: "nature--mountain"
    26: "nature--sand"
    27: "nature--sky"
    28: "nature--snow"
    29: "nature--terrain"
    30: "nature--vegetation"
    31: "nature--water"
    32: "object--banner"
    33: "object--bench"
    34: "object--bike-rack"
    35: "object--billboard"
    36: "object--catch-basin"
    37: "object--cctv-camera"
    38: "object--fire-hydrant"
    39: "object--junction-box"
    40: "object--mailbox"
    41: "object--manhole"
    42: "object--phone-booth"
    43: "object--pothole"
    44: "object--street-light"
    45: "object--support--pole"
    46: "object--support--traffic-sign-frame"
    47: "object--support--utility-pole"
    48: "object--traffic-light"
    49: "object--traffic-sign--back"
    50: "object--traffic-sign--front"
    51: "object--trash-can"
    52: "object--vehicle--bicycle"
    53: "object--vehicle--boat"
    54: "object--vehicle--bus"
    55: "object--vehicle--car"
    56: "object--vehicle--caravan"
    57: "object--vehicle--motorcycle"
    58: "object--vehicle--on-rails"
    59: "object--vehicle--other-vehicle"
    60: "object--vehicle--trailer"
    61: "object--vehicle--truck"
    62: "object--vehicle--wheeled-slow"
    63: "void--car-mount"
    64: "void--ego-vehicle"
    65: "void--unlabeled"
  color_map: # bgr
    0: [42, 42, 165]
    1: [42, 42, 165]
    2: [100, 100, 100]
    3: [100, 100, 100]
    4: [100, 100, 100]
    5: [100, 100, 100]
    6: [100, 100, 100]
    7: [232, 35, 244]
    8: [128, 64, 128]
    9: [128, 64, 128]
    10: [232, 35, 244]
    11: [128, 64, 128]
    12: [128, 64, 128]
    13: [232, 35, 244]
    14: [128, 64, 128]
    15: [128, 64, 128]
    16: [100, 100, 100]
    17: [100, 100, 100]
    18: [100, 100, 100]
    19: [0, 0, 255]
    20: [0, 0, 255]
    21: [0, 0, 255]
    22: [0, 0, 255]
    23: [232, 35, 244]
    24: [232, 35, 244]
    25: [0, 170, 0]
    26: [0, 170, 0]
    27: [180, 130, 70]
    28: [0, 170, 0]
    29: [0, 170, 0]
    30: [0, 170, 0]
    31: [30, 170, 0]
    32: [128, 255, 255]
    33: [128, 255, 255]
    34: [128, 255, 255]
    35: [128, 255, 255]
    36: [128, 255, 255]
    37: [128, 255, 255]
    38: [128, 255, 255]
    39: [128, 255, 255]
    40: [128, 255, 255]
    41: [128, 255, 255]
    42: [128, 255, 255]
    43: [128, 255, 255]
    44: [128, 255, 255]
    45: [205, 205, 205]
    46: [205, 205, 205]
    47: [205, 205, 205]
    48: [30, 170, 250]
    49: [0, 220, 220]
    50: [0, 220, 220]
    51: [0, 220, 220]
    52: [32, 11, 119]
    53: [142, 0, 0]
    54: [142, 0, 0]
    55: [142, 0, 0]
    56: [142, 0, 0]
    57: [32, 11, 119]
    58: [142, 0, 0]
    59: [142, 0, 0]
    60: [142, 0, 0]
    61: [142, 0, 0]
    62: [142, 0, 0]
    63: [142, 0, 0]
    64: [0, 0, 0]
    65: [0, 0, 0]